# Generated by Django 3.2.9 on 2022-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220102_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
