# Generated by Django 3.2.9 on 2022-08-06 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(blank=True, max_length=200, null=True)),
                ('cat', models.CharField(blank=True, max_length=200, null=True)),
                ('numberInStock', models.IntegerField(default=1)),
                ('displayImagePath', models.ImageField(blank=True, default='default_display_pics.jpg', upload_to='gameon/vendor/rental/games/displayImagePath/')),
                ('bannerImagePath', models.ImageField(blank=True, default='default_banner_pics.jpg', upload_to='gameon/vendor/rental/games/bannerImagePath/')),
                ('thumbnailImagePath', models.ImageField(blank=True, default='default_thumbnail_pics.jpg', upload_to='gameon/vendor/rental/games/thumbnailImagePath/')),
                ('dailyRentalRate', models.IntegerField(default=1000)),
                ('adminOwned', models.BooleanField(default=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_code', models.CharField(blank=True, max_length=200, null=True)),
                ('comingSoon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
