# Generated by Django 3.2.9 on 2022-08-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_shop_name'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalgame',
            name='vendor_code',
        ),
        migrations.AlterField(
            model_name='rentalgame',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_game_vendor', to='users.profile'),
        ),
    ]
