# Generated by Django 3.2.9 on 2022-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20220806_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalgame',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
