# Generated by Django 3.2.9 on 2022-08-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rentalgame_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalgame',
            name='adminOwned',
        ),
        migrations.AddField(
            model_name='rentalgame',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
