# Generated by Django 3.2.9 on 2021-12-31 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('cat', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('displayImagePath', models.ImageField(blank=True, default='default_display_pics.jpg', upload_to='vendor/gameon/shop/games/displayImagePath/')),
                ('bannerImagePath', models.ImageField(blank=True, default='default_banner_pics.jpg', upload_to='vendor/gameon/shop/games/bannerImagePath/')),
                ('thumbnailImagePath', models.ImageField(blank=True, default='default_thumbnail_pics.jpg', upload_to='vendor/gameon/shop/games/thumbnailImagePath/')),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('admin_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
